// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Infrastructure.Data;

#nullable disable

namespace Restaurant.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610134855_AddMoreMenuItems")]
    partial class AddMoreMenuItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Restaurant.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Restaurant.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Starters"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Pasta"
                        });
                });

            modelBuilder.Entity("Restaurant.Core.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Grilled bread topped with tomatoes, garlic, fresh basil, and olive oil.",
                            ImageUrl = "/images/menu/bruschetta.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Bruschetta",
                            Price = 7.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Crisp romaine, parmesan, croutons, and our house Caesar dressing.",
                            ImageUrl = "/images/menu/caesar.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Caesar Salad",
                            Price = 9.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Oven-baked baguette with garlic butter and a touch of parsley.",
                            ImageUrl = "/images/menu/garlic-bread.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Garlic Bread",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Golden, crispy breaded mozzarella served with marinara dip.",
                            ImageUrl = "/images/menu/mozzarella-sticks.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Mozzarella Sticks",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Crispy wings tossed in your choice of buffalo or BBQ sauce.",
                            ImageUrl = "/images/menu/chicken-wings.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chicken Wings",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Creamy roasted-tomato soup with basil and a swirl of cream.",
                            ImageUrl = "/images/menu/tomato-soup.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Tomato Soup",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Atlantic salmon, lemon-butter glaze, served with seasonal vegetables.",
                            ImageUrl = "/images/menu/salmon.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Grilled Salmon",
                            Price = 22.50m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "12oz prime ribeye, garlic butter, mashed potato, roasted asparagus.",
                            ImageUrl = "/images/menu/ribeye.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Ribeye Steak",
                            Price = 32.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Wood-fired pizza with tomato, fresh mozzarella, and basil.",
                            ImageUrl = "/images/menu/margherita-pizza.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Margherita Pizza",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Beef patty, cheddar, lettuce, tomato, and house sauce with fries.",
                            ImageUrl = "/images/menu/cheeseburger.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cheeseburger",
                            Price = 13.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Herb-marinated chicken breast with grilled vegetables.",
                            ImageUrl = "/images/menu/grilled-chicken.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Grilled Chicken",
                            Price = 16.50m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Beer-battered cod with thick-cut chips and tartar sauce.",
                            ImageUrl = "/images/menu/fish-and-chips.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Fish and Chips",
                            Price = 14.50m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Slow-cooked pork ribs glazed in smoky barbecue sauce.",
                            ImageUrl = "/images/menu/bbq-ribs.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "BBQ Ribs",
                            Price = 19.50m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Layered espresso-soaked ladyfingers with mascarpone and cocoa.",
                            ImageUrl = "/images/menu/tiramisu.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Tiramisu",
                            Price = 8.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Warm dark-chocolate cake with a molten centre, served with vanilla ice cream.",
                            ImageUrl = "/images/menu/lava.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chocolate Lava Cake",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Creamy New York-style cheesecake with a berry compote.",
                            ImageUrl = "/images/menu/cheesecake.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cheesecake",
                            Price = 7.50m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Warm spiced apple pie with a flaky crust and vanilla ice cream.",
                            ImageUrl = "/images/menu/apple-pie.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Apple Pie",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Vanilla ice cream, chocolate sauce, nuts, and whipped cream.",
                            ImageUrl = "/images/menu/ice-cream-sundae.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Ice Cream Sundae",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Glass of our house red, full-bodied with a smooth finish.",
                            ImageUrl = "/images/menu/red-wine.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "House Red Wine",
                            Price = 7.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Chilled sparkling mineral water with lemon.",
                            ImageUrl = "/images/menu/sparkling.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Sparkling Water",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "Classic ice-cold cola served with lemon.",
                            ImageUrl = "/images/menu/coca-cola.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Coca-Cola",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Description = "Freshly squeezed orange juice.",
                            ImageUrl = "/images/menu/orange-juice.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Orange Juice",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            Description = "Espresso with steamed milk and a thick layer of foam.",
                            ImageUrl = "/images/menu/cappuccino.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cappuccino",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Description = "Homemade lemonade with fresh mint.",
                            ImageUrl = "/images/menu/lemonade.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Lemonade",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Description = "Locally brewed craft lager, served chilled.",
                            ImageUrl = "/images/menu/craft-beer.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Craft Beer",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Description = "Rum, lime, mint, and soda over crushed ice.",
                            ImageUrl = "/images/menu/mojito.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Mojito",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "Rich single-shot espresso.",
                            ImageUrl = "/images/menu/espresso.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Espresso",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "Refreshing iced tea with lemon.",
                            ImageUrl = "/images/menu/iced-tea.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Iced Tea",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Classic Roman pasta with guanciale, egg, pecorino, and black pepper.",
                            ImageUrl = "/images/menu/carbonara.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Spaghetti Carbonara",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "Penne in a spicy tomato sauce with garlic and chili.",
                            ImageUrl = "/images/menu/arrabbiata.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Penne Arrabbiata",
                            Price = 13.50m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Description = "Layers of pasta, beef ragù, béchamel, and melted cheese.",
                            ImageUrl = "/images/menu/lasagna.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Lasagna",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Description = "Fettuccine in a creamy parmesan and butter sauce.",
                            ImageUrl = "/images/menu/fettuccine-alfredo.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Fettuccine Alfredo",
                            Price = 13.00m
                        });
                });

            modelBuilder.Entity("Restaurant.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuestsCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialRequest")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationDate");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Restaurant.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Restaurant.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Restaurant.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Core.Entities.MenuItem", b =>
                {
                    b.HasOne("Restaurant.Core.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.Order", b =>
                {
                    b.HasOne("Restaurant.Core.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Restaurant.Core.Entities.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.Reservation", b =>
                {
                    b.HasOne("Restaurant.Core.Entities.ApplicationUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Restaurant.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
